name: Release

on:
  workflow_dispatch:
    inputs:
      draft-release:
        type: boolean
        default: true
        description: Whether to publish the release as a draft.

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: release

jobs:
  package:
    uses: ./.github/workflows/package.yaml
    secrets: inherit

  release:
    needs: [package]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download installers
        uses: actions/download-artifact@v4
        with:
          name: installers
          path: out/

      - name: Semantic release
        uses: glzr-io/actions/semantic-release@main
        with:
          gh-publish: true
          gh-draft-release: ${{ inputs.draft-release }}
          gh-token: ${{ github.token }}
          gh-assets: |
            [
              {
                "path": "out/installer-universal",
                "name": "glazewm-${nextRelease.gitTag}-opt0",
                "label": "${nextRelease.gitTag} Installer (recommended)"
              },
              {
                "path": "out/installer-x64",
                "name": "glazewm-${nextRelease.gitTag}-opt1-x64",
                "label": "${nextRelease.gitTag} Installer (standalone x64)"
              },
              {
                "path": "out/installer-arm64",
                "name": "glazewm-${nextRelease.gitTag}-opt1-arm64",
                "label": "${nextRelease.gitTag} Installer (standalone arm64)"
              }
            ]
            
      - name: Winget Release
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: glzr-io.glazewm
          installers-regex: 'glazewm-[0-9.]+\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
